version: "3"

services:

  sensu-server:
    build: sensu-server
    volumes:
    - $PWD/sensu-server/checks/check-docker.json:/etc/sensu/conf.d/check-docker.json
    - $PWD/sensu-server/checks/check-disk-usage.json:/etc/sensu/conf.d/check-disk-usage.json
    - $PWD/sensu-server/checks/check-memory-usage.json:/etc/sensu/conf.d/check-memory-usage.json
    - $PWD/sensu-server/checks/check-server-uptime.json:/etc/sensu/conf.d/check-server-uptime.json
    ports:
    - 4567:4567  # API PORT
    environment:
    - SENSU_USER
    - SENSU_PASSWORD
    depends_on:
    - rabbitmq

  rabbitmq:
    image: rabbitmq:3.6-alpine
    environment: 
    - RABBITMQ_DEFAULT_USER=$SENSU_USER
    - RABBITMQ_DEFAULT_PASS=$SENSU_PASSWORD
    - RABBITMQ_DEFAULT_VHOST=/sensu
    - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=0.8
    ports:
    - 5672:5672    # rabbitmq api
    - 15672:15672  # rabbitmq console
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"

  uchiwa:
    image: uchiwa/uchiwa
    volumes:
    - $PWD/sensu-server/config/uchiwa.json:/config/config.json
    depends_on:
    - sensu-server
    ports:
    - 3000:3000  # WEB UI PORT (uchiwa)
  sensu-client:
    build: sensu-client
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - $PWD/sensu-client/plugins:/etc/sensu/plugins
    - $CLIENT_MOUNT1:/mnt/mount1
    - $CLIENT_MOUNT2:/mnt/mount2
    privileged: true
    environment:
    - SENSU_HOST
    - SENSU_USER
    - SENSU_PASSWORD
    - CLIENT_NAME
    - CLIENT_IP
